### ISSUE TITLE
Модель не полная?

### ISSUE THREAD

**Issue by wmakeev** [moysklad/java-remap-1.2-sdk#4]
Генерирую JSON представление модели из текущего SDK. Заметил что не хватает некоторых полей в сущностях. Получается, что описание не полное?

**Comment by ipivkin** [comment]
Все верно, СДК пока неполное

**Comment by wmakeev** [comment]
Т.е., больше никак не получить актуальную информацию по модели? 
Возможно ли присылать pull-реквесты на добавление полей?
Или, всё же, есть некий основной источник истины по структуре классов и полям откуда можно взять данные?
